### ISSUE TITLE
when i run wcdl i got this error

### ISSUE THREAD

**Issue by lscjiroot** [terminalforlife/PerlProjects#2]
Can't unlink('https://wallpaperscraft.com'): No such file or directory at wcdl line 197

**Comment by terminalforlife** [comment]
Thanks for reporting the bug. Which version of WCDL are you using? Also, can you show me the command you ran which got that result? Lastly, can you post the output of `lsb_release -ds || uname -v`?

**Comment by lscjiroot** [comment]
lsb_release -ds || uname -v = "Manjaro Linux"
perl wcdl -D ./images/ -N nature '1' = "Can't unlink('https://wallpaperscraft.com'): No such file or directory at wcdl line 198"
perl wcdl -v = 2020-01-15"

**Comment by terminalforlife** [comment]
It looks like the version in the dev branch has at some point addressed that bug, as it worked for me, so you could either install that one (`cito -r terminalforlife PerlProjects dev source/wcdl`) or hold out for tomorrow, when I'll hopefully have updated WCDL some mode and pushed it out to master when I'm happy with it.

Please let me know how the dev version works, if you install that, or let me know tomorrow if you decide to wait, as I'd like to know if the bug is something else.

**Comment by lscjiroot** [comment]
Thanks i try it on i be on home

**Comment by lscjiroot** [comment]
is there new videos

**Comment by terminalforlife** [comment]
> is there new videos

Not yet.

> Thanks i try it on i be on home

Be sure to let me know if the bug is fixed for you.

**Comment by lscjiroot** [comment]
still same problem

**Comment by lscjiroot** [comment]
Do you have link wcdl fixed problem ?

**Comment by terminalforlife** [comment]
Okay, I see what's going on. Hopefully it'll be patched very soon. For now, omit `-N` (in other words, use the caching system), which will allow it to work.
